/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hopen.SistemaHopen.UI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lisan
 */
public class CargarPresupuesto extends javax.swing.JFrame {

    /**
     * Creates new form CargarPresupuestoPrueba
     */
    public CargarPresupuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        tabAluminio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        presupuestoKg = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        presupuestoAlu = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        remito = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        guardarAluminio = new javax.swing.JButton();
        SalirBtn = new javax.swing.JButton();
        tabVidro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        planchasVidrio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        presupuestoVidrio = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        guardarVidrio = new javax.swing.JButton();
        SalirBtn1 = new javax.swing.JButton();
        tabAcc = new javax.swing.JPanel();
        guardarAcc = new javax.swing.JButton();
        SalirBtn2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        presupuestoAcc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        fechaAcc = new com.toedter.calendar.JDateChooser();
        tabManoObra = new javax.swing.JPanel();
        guardarManoObra = new javax.swing.JButton();
        SalirBtn3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cantidadHoras = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        presupuestoManoObra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        tabViaje = new javax.swing.JPanel();
        guardarViajes = new javax.swing.JButton();
        SalirBtn4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cantidadViajes = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        presupuestoViajes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jTabbedPane6.setBackground(new java.awt.Color(51, 204, 255));
        jTabbedPane6.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        tabAluminio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kilos Presupuestado");

        presupuestoKg.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        presupuestoKg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        presupuestoKg.setBorder(null);
        presupuestoKg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        presupuestoKg.setSelectionColor(new java.awt.Color(51, 204, 255));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pesos Presupuestados");

        presupuestoAlu.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        presupuestoAlu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        presupuestoAlu.setBorder(null);
        presupuestoAlu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        presupuestoAlu.setSelectionColor(new java.awt.Color(51, 204, 255));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Remito");

        remito.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        remito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        remito.setBorder(null);
        remito.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        remito.setSelectionColor(new java.awt.Color(51, 204, 255));

        guardarAluminio.setBackground(new java.awt.Color(0, 204, 255));
        guardarAluminio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        guardarAluminio.setForeground(new java.awt.Color(255, 255, 255));
        guardarAluminio.setText("Guardar");
        guardarAluminio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarAluminio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAluminioActionPerformed(evt);
            }
        });

        SalirBtn.setBackground(new java.awt.Color(255, 153, 51));
        SalirBtn.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        SalirBtn.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn.setText("Volver");
        SalirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAluminioLayout = new javax.swing.GroupLayout(tabAluminio);
        tabAluminio.setLayout(tabAluminioLayout);
        tabAluminioLayout.setHorizontalGroup(
            tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAluminioLayout.createSequentialGroup()
                .addGroup(tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAluminioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(presupuestoKg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAluminioLayout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAluminioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(presupuestoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAluminioLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remito, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAluminioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guardarAluminio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabAluminioLayout.setVerticalGroup(
            tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAluminioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(presupuestoKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(presupuestoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(remito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(tabAluminioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAluminio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Aluminio", tabAluminio);

        tabVidro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad Planchas");

        planchasVidrio.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        planchasVidrio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        planchasVidrio.setBorder(null);
        planchasVidrio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        planchasVidrio.setSelectionColor(new java.awt.Color(51, 204, 255));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pesos Presupuestados");

        presupuestoVidrio.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        presupuestoVidrio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        presupuestoVidrio.setBorder(null);
        presupuestoVidrio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        presupuestoVidrio.setSelectionColor(new java.awt.Color(51, 204, 255));

        guardarVidrio.setBackground(new java.awt.Color(0, 204, 255));
        guardarVidrio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        guardarVidrio.setForeground(new java.awt.Color(255, 255, 255));
        guardarVidrio.setText("Guardar");
        guardarVidrio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarVidrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarVidrioActionPerformed(evt);
            }
        });

        SalirBtn1.setBackground(new java.awt.Color(255, 153, 51));
        SalirBtn1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        SalirBtn1.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn1.setText("Volver");
        SalirBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabVidroLayout = new javax.swing.GroupLayout(tabVidro);
        tabVidro.setLayout(tabVidroLayout);
        tabVidroLayout.setHorizontalGroup(
            tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVidroLayout.createSequentialGroup()
                .addGroup(tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabVidroLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabVidroLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addComponent(planchasVidrio, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabVidroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(presupuestoVidrio)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabVidroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarVidrio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalirBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabVidroLayout.setVerticalGroup(
            tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVidroLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(planchasVidrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(presupuestoVidrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(tabVidroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarVidrio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Vidrio", tabVidro);

        tabAcc.setBackground(new java.awt.Color(255, 255, 255));

        guardarAcc.setBackground(new java.awt.Color(0, 204, 255));
        guardarAcc.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        guardarAcc.setForeground(new java.awt.Color(255, 255, 255));
        guardarAcc.setText("Guardar");
        guardarAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAccActionPerformed(evt);
            }
        });

        SalirBtn2.setBackground(new java.awt.Color(255, 153, 51));
        SalirBtn2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        SalirBtn2.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn2.setText("Volver");
        SalirBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtn2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fecha de Compra");

        presupuestoAcc.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        presupuestoAcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        presupuestoAcc.setBorder(null);
        presupuestoAcc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        presupuestoAcc.setSelectionColor(new java.awt.Color(51, 204, 255));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pesos Presupuestados");

        javax.swing.GroupLayout tabAccLayout = new javax.swing.GroupLayout(tabAcc);
        tabAcc.setLayout(tabAccLayout);
        tabAccLayout.setHorizontalGroup(
            tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAccLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAccLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guardarAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalirBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabAccLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabAccLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(54, 54, 54)
                                .addGroup(tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)))))
                    .addGroup(tabAccLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(50, 50, 50)
                        .addComponent(presupuestoAcc)))
                .addContainerGap())
        );
        tabAccLayout.setVerticalGroup(
            tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAccLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(fechaAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(presupuestoAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(tabAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Accesorios", tabAcc);

        tabManoObra.setBackground(new java.awt.Color(255, 255, 255));

        guardarManoObra.setBackground(new java.awt.Color(0, 204, 255));
        guardarManoObra.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        guardarManoObra.setForeground(new java.awt.Color(255, 255, 255));
        guardarManoObra.setText("Guardar");
        guardarManoObra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarManoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarManoObraActionPerformed(evt);
            }
        });

        SalirBtn3.setBackground(new java.awt.Color(255, 153, 51));
        SalirBtn3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        SalirBtn3.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn3.setText("Volver");
        SalirBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtn3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cantidad Horas");

        cantidadHoras.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        cantidadHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadHoras.setBorder(null);
        cantidadHoras.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantidadHoras.setSelectionColor(new java.awt.Color(51, 204, 255));

        presupuestoManoObra.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        presupuestoManoObra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        presupuestoManoObra.setBorder(null);
        presupuestoManoObra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        presupuestoManoObra.setSelectionColor(new java.awt.Color(51, 204, 255));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pesos Presupuestados");

        javax.swing.GroupLayout tabManoObraLayout = new javax.swing.GroupLayout(tabManoObra);
        tabManoObra.setLayout(tabManoObraLayout);
        tabManoObraLayout.setHorizontalGroup(
            tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabManoObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabManoObraLayout.createSequentialGroup()
                        .addGap(0, 337, Short.MAX_VALUE)
                        .addComponent(guardarManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalirBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabManoObraLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabManoObraLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(37, 37, 37)
                                .addComponent(cantidadHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabManoObraLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(50, 50, 50)
                        .addComponent(presupuestoManoObra)))
                .addContainerGap())
        );
        tabManoObraLayout.setVerticalGroup(
            tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabManoObraLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cantidadHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(presupuestoManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(tabManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Mano de Obra", tabManoObra);

        tabViaje.setBackground(new java.awt.Color(255, 255, 255));

        guardarViajes.setBackground(new java.awt.Color(0, 204, 255));
        guardarViajes.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        guardarViajes.setForeground(new java.awt.Color(255, 255, 255));
        guardarViajes.setText("Guardar");
        guardarViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarViajesActionPerformed(evt);
            }
        });

        SalirBtn4.setBackground(new java.awt.Color(255, 153, 51));
        SalirBtn4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        SalirBtn4.setForeground(new java.awt.Color(255, 255, 255));
        SalirBtn4.setText("Volver");
        SalirBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SalirBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtn4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cantidad Viajes");

        cantidadViajes.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        cantidadViajes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidadViajes.setBorder(null);
        cantidadViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cantidadViajes.setSelectionColor(new java.awt.Color(51, 204, 255));

        presupuestoViajes.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        presupuestoViajes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        presupuestoViajes.setBorder(null);
        presupuestoViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        presupuestoViajes.setSelectionColor(new java.awt.Color(51, 204, 255));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pesos Presupuestados");

        javax.swing.GroupLayout tabViajeLayout = new javax.swing.GroupLayout(tabViaje);
        tabViaje.setLayout(tabViajeLayout);
        tabViajeLayout.setHorizontalGroup(
            tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabViajeLayout.createSequentialGroup()
                        .addGap(0, 337, Short.MAX_VALUE)
                        .addComponent(guardarViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SalirBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabViajeLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabViajeLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37)
                                .addComponent(cantidadViajes, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabViajeLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(50, 50, 50)
                        .addComponent(presupuestoViajes)))
                .addContainerGap())
        );
        tabViajeLayout.setVerticalGroup(
            tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabViajeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cantidadViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(presupuestoViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(tabViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalirBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane6.addTab("Viajes", tabViaje);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane6.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarAluminioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAluminioActionPerformed
        // TODO add your handling code here:
        double kiloPresupuestado = Double.parseDouble(presupuestoKg.getText());
        String rto = remito.getText();
        Double totalPresupuestado = Double.parseDouble(presupuestoAlu.getText());

        PreparedStatement ps;

        try{
            Connection con = ConexionDB.getConnection();
            String sql ="INSERT INTO aluminio (total_presupuesto, remito, kilo_presupuestado) VALUES (?,?,?)";
            ps = ConexionDB.getConnection().prepareStatement(sql);

            ps.setDouble(1, totalPresupuestado);
            ps.setString(2, rto);
            ps.setDouble(3, kiloPresupuestado);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos guardados");
            ConexionDB.endConnection(con);

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_guardarAluminioActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Si vuelve atras no se guardarán los datos.", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)
            == JOptionPane.YES_OPTION){
            try {
                new CargarObra().setVisible(true);
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(CargarObra.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void guardarVidrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarVidrioActionPerformed
        // TODO add your handling code here:
        int cantPlanchas = Integer.parseInt(planchasVidrio.getText());
        Double totalPresupuestado = Double.parseDouble(presupuestoAlu.getText());

        PreparedStatement ps;

        try{
            Connection con = ConexionDB.getConnection();
            String sql ="INSERT INTO vidrio (total_presupuesto, cant_planchas) VALUES (?,?)";
            ps = ConexionDB.getConnection().prepareStatement(sql);

            ps.setDouble(1, totalPresupuestado);
            ps.setInt(2, cantPlanchas);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos guardados");
            ConexionDB.endConnection(con);

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_guardarVidrioActionPerformed

    private void SalirBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtn1ActionPerformed
        // TODO add your handling code here:
        new CargarObra().setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirBtn1ActionPerformed

    private void guardarAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAccActionPerformed
        // TODO add your handling code here:
        java.util.Date fecha = fechaAcc.getDate();
        long timeInMilliSecs = fecha.getTime();
        java.sql.Date fechaDB = new java.sql.Date(timeInMilliSecs);
        Double totalPresupuestado = Double.parseDouble(presupuestoAlu.getText());

        PreparedStatement ps;

        try{
            Connection con = ConexionDB.getConnection();
            String sql ="INSERT INTO accesorio (total_presupuesto, fecha_compra) VALUES (?,?)";
            ps = ConexionDB.getConnection().prepareStatement(sql);

            ps.setDouble(1, totalPresupuestado);
            ps.setDate(2, fechaDB);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos guardados");
            ConexionDB.endConnection(con);

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_guardarAccActionPerformed

    private void SalirBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtn2ActionPerformed
        // TODO add your handling code here:
        new CargarObra().setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirBtn2ActionPerformed

    private void guardarManoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarManoObraActionPerformed
        // TODO add your handling code here:
        int cantHoras = Integer.parseInt(cantidadHoras.getText());
        Double totalPresupuestado = Double.parseDouble(presupuestoAlu.getText());

        PreparedStatement ps;

        try{
            Connection con = ConexionDB.getConnection();
            String sql ="INSERT INTO mano_obra (total_presupuesto, horasmo) VALUES (?,?)";
            ps = ConexionDB.getConnection().prepareStatement(sql);

            ps.setDouble(1, totalPresupuestado);
            ps.setInt(2, cantHoras);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos guardados");
            ConexionDB.endConnection(con);

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_guardarManoObraActionPerformed

    private void SalirBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtn3ActionPerformed
        // TODO add your handling code here:
        new CargarObra().setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirBtn3ActionPerformed

    private void guardarViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarViajesActionPerformed
        // TODO add your handling code here:
        int cantViajes = Integer.parseInt(cantidadViajes.getText());
        Double totalPresupuestado = Double.parseDouble(presupuestoAlu.getText());

        PreparedStatement ps;

        try{
            Connection con = ConexionDB.getConnection();
            String sql ="INSERT INTO viaje (total_presupuesto, fecha_compra) VALUES (?,?)";
            ps = ConexionDB.getConnection().prepareStatement(sql);

            ps.setDouble(1, totalPresupuestado);
            ps.setInt(2, cantViajes);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Datos guardados");
            ConexionDB.endConnection(con);

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_guardarViajesActionPerformed

    private void SalirBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtn4ActionPerformed
        // TODO add your handling code here:
        new CargarObra().setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalirBtn;
    private javax.swing.JButton SalirBtn1;
    private javax.swing.JButton SalirBtn2;
    private javax.swing.JButton SalirBtn3;
    private javax.swing.JButton SalirBtn4;
    private javax.swing.JTextField cantidadHoras;
    private javax.swing.JTextField cantidadViajes;
    private com.toedter.calendar.JDateChooser fechaAcc;
    private javax.swing.JButton guardarAcc;
    private javax.swing.JButton guardarAluminio;
    private javax.swing.JButton guardarManoObra;
    private javax.swing.JButton guardarViajes;
    private javax.swing.JButton guardarVidrio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField planchasVidrio;
    private javax.swing.JTextField presupuestoAcc;
    private javax.swing.JTextField presupuestoAlu;
    private javax.swing.JTextField presupuestoKg;
    private javax.swing.JTextField presupuestoManoObra;
    private javax.swing.JTextField presupuestoViajes;
    private javax.swing.JTextField presupuestoVidrio;
    private javax.swing.JTextField remito;
    private javax.swing.JPanel tabAcc;
    private javax.swing.JPanel tabAluminio;
    private javax.swing.JPanel tabManoObra;
    private javax.swing.JPanel tabViaje;
    private javax.swing.JPanel tabVidro;
    // End of variables declaration//GEN-END:variables
}
